create table tb_ingrediente (id  bigserial not null, nome varchar(255), preco float8, primary key (id));
create table tb_item_pedido (id  bigserial not null, preco_ingrediente float8, ingrediente_id int8, pedido_id int8, primary key (id));
create table tb_lanche (id  bigserial not null, nome varchar(255), primary key (id));
create table tb_lanche_ingrediente (lanche_id int8 not null, ingrediente_id int8 not null);
create table tb_pedido (id  bigserial not null, valor_total float8, lanche_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_user (id  bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_item_pedido add constraint FKdft3ssm8qaulogl9ehnkm60wl foreign key (ingrediente_id) references tb_ingrediente;
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido;
alter table tb_lanche_ingrediente add constraint FK28eqc8nk7cakkrod0o3r673h7 foreign key (ingrediente_id) references tb_ingrediente;
alter table tb_lanche_ingrediente add constraint FKfkkho8kspd2wt9b91ell7d4qa foreign key (lanche_id) references tb_lanche;
alter table tb_pedido add constraint FK6lv7d4k51i0m20ajjxiqjrryu foreign key (lanche_id) references tb_lanche;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_ingrediente (nome, preco) VALUES ('ALFACE', '0.4');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('BACON', '2');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('HAMBURGUER', '3');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('OVO', '0.8');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('QUEIJO', '1.5');
INSERT INTO tb_lanche (nome) VALUES ('X-BACON');
INSERT INTO tb_lanche (nome) VALUES ('X-BURGUER');
INSERT INTO tb_lanche (nome) VALUES ('X-EGG');
INSERT INTO tb_lanche (nome) VALUES ('X-EGG BACON');
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,2);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (2,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (2,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,4);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,2);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,4);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,5);
create table tb_ingrediente (id  bigserial not null, nome varchar(255), preco float8, primary key (id));
create table tb_item_pedido (id  bigserial not null, preco_ingrediente float8, ingrediente_id int8, pedido_id int8, primary key (id));
create table tb_lanche (id  bigserial not null, nome varchar(255), primary key (id));
create table tb_lanche_ingrediente (lanche_id int8 not null, ingrediente_id int8 not null);
create table tb_pedido (id  bigserial not null, valor_total float8, lanche_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_user (id  bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_item_pedido add constraint FKdft3ssm8qaulogl9ehnkm60wl foreign key (ingrediente_id) references tb_ingrediente;
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido;
alter table tb_lanche_ingrediente add constraint FK28eqc8nk7cakkrod0o3r673h7 foreign key (ingrediente_id) references tb_ingrediente;
alter table tb_lanche_ingrediente add constraint FKfkkho8kspd2wt9b91ell7d4qa foreign key (lanche_id) references tb_lanche;
alter table tb_pedido add constraint FK6lv7d4k51i0m20ajjxiqjrryu foreign key (lanche_id) references tb_lanche;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_ingrediente (nome, preco) VALUES ('ALFACE', '0.4');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('BACON', '2');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('HAMBURGUER', '3');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('OVO', '0.8');
INSERT INTO tb_ingrediente (nome, preco) VALUES ('QUEIJO', '1.5');
INSERT INTO tb_lanche (nome) VALUES ('X-BACON');
INSERT INTO tb_lanche (nome) VALUES ('X-BURGUER');
INSERT INTO tb_lanche (nome) VALUES ('X-EGG');
INSERT INTO tb_lanche (nome) VALUES ('X-EGG BACON');
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,2);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (1,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (2,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (2,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,4);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (3,5);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,2);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,3);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,4);
INSERT INTO tb_lanche_ingrediente (lanche_id, ingrediente_id) VALUES (4,5);
